version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mariadb
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=srgaerua"
      - "MYSQL_USER=srgaerua"
      - "MYSQL_PASSWORD=srgaerua"
      - "MYSQL_ROOT_PASSWORD=srgaerua"
    ports:
        - "33061:3306"

  # Elastic Search
  #elasticsearch:
  #  image: elasticsearch

  # Kibana
  #kibana:
  #  image: kibana
  #  ports:
  #      - 5601:5601


volumes:
  dbdata: